version: '3.1'

services:

    mongodb:
        image: mongo:4.4.18
        container_name: mongodb
        #user: root
        ports:
            - "${HOST_PORT}:27017"
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${USER}
            - MONGO_INITDB_ROOT_PASSWORD=${PASS}
        volumes:
             -  ./datadir:/data/db
             -  /etc/ssl/mongo.pem:/etc/ssl/mongo.pem
        command:
             - 'mongod'
             - '--tlsMode'
             - 'requireTLS'
             - '--tlsCertificateKeyFile'
             - '/etc/ssl/mongo.pem'
        
