version: '3.1'

services:

    mongodb:
        image: mongo:4.2.20-rc0-bionic
        container_name: mongodb
        #user: root
        ports:
            - "27016:27017"
        #environment:     
        #     - MONGO_INITDB_ROOT_USERNAME= "root"
        #     - MONGO_INITDB_ROOT_PASSWORD= "example"
        volumes:
             -  ./datadir:/data/db
             -  ./config/mongod.conf.orig:/etc/mongod.conf.orig
        