version: '3.1'

services:

    mongodb:
        image: mongo:4.2.20-rc0-bionic
        container_name: mongodb
        #user: root
        ports:
            - "27015:27017"
        restart: always
        #environment:     
        #     - MONGO_INITDB_ROOT_USERNAME= "root"
        #     - MONGO_INITDB_ROOT_PASSWORD= "example"
        volumes:
             -  ./datadir:/data/db
             -  ./config/mongod.conf.orig:/etc/mongod.conf.orig
        
